version: '3'

services:
  api:
    build: ./app
    ports:
    - "3003:3000"
    volumes:
    - "./app/server.js:/usr/src/app/server.js"
    environment:
    - PORT=8080
    - DNS_NAME=todoapp
    depends_on:
    - todoapp

  todoapp:
    build:
      context: ./todo







